### ISSUE TITLE
Add custom command menu [HELP]

### ISSUE THREAD

**Issue by ParadoxLeon** [prethink/Cs2Telegram#1]
Hi I would love to add a custom menu for changing the level like
```
[
  "ds_workshop_changelevel de_dust2_classic",
  "ds_workshop_changelevel cs_assault",
  "ds_workshop_changelevel de_vandal"
  ]

```

can someone tell me how I would do that?

**Comment by ParadoxLeon** [comment]
when adding a lot of maps to `ServerCommandsMenuItems` I get 
```
13:31:03 [EROR] (plugin:Cs2Telegram) System.Exception: Превышен лимит для callback_data 132 > 128. Попробуйте уменьшить количество данных в команде
   at PRTelegramBot.Models.InlineButtons.InlineCallback.GetContent()
   at PRTelegramBot.Helpers.TG.MenuGenerator.GetInlineButton(IInlineContent inlineData)
   at PRTelegramBot.Helpers.TG.MenuGenerator.InlineButtons(Int32 maxColumn, List`1 menu)
   at Cs2Telegram.Commands.ServerCommands.ExecuteCommandInServer(ITelegramBotClient botClient, Update update) in E:\dev\cs2\Cs2Telegram\Source\Commands\ServerCommands.cs:line 44
   at PRTelegramBot.Core.Router.ExecuteCommandByMessage(String command, Update update)

```

**Comment by prethink** [comment]
Hi, the issue is most likely that the message ds_workshop_changelevel de_dust2_classic is too long. Telegram has limitations for processing inline buttons.

I have an idea to work around this, but the plugin needs to be improved. If you have any other suggestions or ideas for improvements, feel free to share them here.

If I take on the task of improving it, it will only be on the weekends or starting from around December 24th.

**Comment by prethink** [comment]
Hello, check pls new version https://github.com/prethink/Cs2Telegram/releases/tag/v0.3.2

The problem must go away

**Comment by prethink** [comment]
When adding the command ds_workshop_changelevel de_dust2_classic, the menu should display Change de_dust2_classic, similar to when using the regular changelevel.
![изображение](https://github.com/user-attachments/assets/e895f981-4be6-4415-8c16-14d90a9d42aa)

**Comment by ParadoxLeon** [comment]
Nice one :) 
Will test it on the weekend.
